/**
 * Command to create a new regulatory report
 */
export class CreateRegulatoryReportCommand {
  constructor(
    public readonly organizationId: string,
    public readonly reportType: string,
    public readonly regulatoryAgency: string,
    public readonly reportingPeriod: string,
    public readonly reportingPeriodStart: Date,
    public readonly reportingPeriodEnd: Date,
    public readonly dueDate: Date,
    public readonly createdByUserId: string,
    public readonly wellId?: string,
    public readonly reportSubType?: string,
    public readonly priority?: string,
    public readonly gracePeriodEnd?: Date,
    public readonly isAutoGenerated?: boolean,
    public readonly autoSubmissionEnabled?: boolean,
  ) {}
}
