/**
 * Query to get regulatory reports with filtering and pagination
 */
export class GetRegulatoryReportsQuery {
  constructor(
    public readonly organizationId: string,
    public readonly filters?: {
      reportType?: string;
      status?: string;
      regulatoryAgency?: string;
      wellId?: string;
      startDate?: Date;
      endDate?: Date;
      priority?: string;
      isOverdue?: boolean;
      isAutoGenerated?: boolean;
    },
    public readonly pagination?: {
      page?: number;
      limit?: number;
    },
    public readonly sort?: {
      field?: string;
      direction?: 'asc' | 'desc';
    },
  ) {}
}
